### ISSUE TITLE
Enhancement: Conversion of Seeed OPL Eagle libraries?

### ISSUE THREAD

**Issue by haebler** [lachlanA/eagle-to-kicad-libs#1]
Any chance you can convert all the Seeed Studio OPL Eagle libraries to KiCAD and provide them as examples?

Library page:
[http://www.seeedstudio.com/depot/OPLopen-parts-library-catalog-c-136_138/?ref=side]

Actual libraries as .zip:
[http://www.seeedstudio.com/wiki/File:OPL_eagle_library.zip]

**Comment by lachlanA** [comment]
Hi sorry for the very late replay, will look into it..

**Comment by lachlanA** [comment]
I have add the libs to the examples
as always flower the,  Russian proverb, measure seven times, cut once.
Lachlan
