### ISSUE TITLE
Only one footprint in mod file after conversion

### ISSUE THREAD

**Issue by mp035** [lachlanA/eagle-to-kicad-libs#8]
Hi, first of all, thank you for this tool it is a real time saver.

I have an issue when I try to convert my eagle library with 13 footprints in it.  The conversion completes without error, and all of the schematic symbols convert ok, however when I open the .mod file in kicad, only one footprint is accessible.  When I open the .mod file in a text editor, I can see the other footprints, but kicad doesn't find them.  The generated .mod file in question is attached.
[custom_module.zip](https://github.com/lachlanA/eagle-to-kicad-libs/files/1381261/custom_module.zip)

**Comment by mp035** [comment]
Interestingly, If I manually edit the mod file with a text editor so that only one footprint is left, then kicad can see that footprint.  As a work around I am manually separating the generated mod file into multiple mod files, each one containing a single footprint.

**Comment by mp035** [comment]
Found the problem.  I had a library naming conflict which was causing the issue.  It is not a problem with your converter.

**Comment by lachlanA** [comment]
Thanks for the info !
Glad it's working for you :)
Lachlan
